version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    env_file: .env
    environment:
      NODE_ENV: production
      DB_HOST: postgres
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  users-service:
    build:
      context: .
      dockerfile: apps/users-service/Dockerfile
    env_file: .env
    environment:
      NODE_ENV: production
      DB_HOST: postgres
    depends_on:
      - postgres

  core-service:
    build:
      context: .
      dockerfile: apps/core-service/Dockerfile
    env_file: .env
    environment:
      NODE_ENV: production
      DB_HOST: postgres
    depends_on:
      - postgres

volumes:
  postgres_data:
