version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-dev
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  users-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: users-service-dev
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: yarn dev:users
    ports:
      - "4001:4001"
    depends_on:
      - db

  core-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: core-service-dev
    env_file:
      - .env
    volumes:
      - ./:/app
    working_dir: /app
    command: yarn dev:core
    ports:
      - "4002:4002"
    depends_on:
      - db

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-gateway-dev
    env_file:
      - .env
    volumes:
      - ./:/app
    working_dir: /app
    command: yarn dev:gateway
    ports:
      - "3000:3000"
    depends_on:
      - users-service
      - core-service

volumes:
  postgres-data:
