version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    env_file: .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust   # для быстрого старта в dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile.dev
    volumes:
      - ./:/app:cached
      - /app/node_modules
    working_dir: /app
    command: yarn dev:gateway
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - users-service
      - core-service

  users-service:
    build:
      context: .
      dockerfile: apps/users-service/Dockerfile.dev
    volumes:
      - ./:/app:cached
      - /app/node_modules
    working_dir: /app
    command: yarn dev:users
    env_file: .env
    ports:
      - "4001:4001"
    depends_on:
      - postgres

  core-service:
    build:
      context: .
      dockerfile: apps/core-service/Dockerfile.dev
    volumes:
      - ./:/app:cached
      - /app/node_modules
    working_dir: /app
    command: yarn dev:core
    env_file: .env
    ports:
      - '4002:4002'
    depends_on:
      - postgres

volumes:
  postgres_data:
